name: Codacy Analysis CLI

on: ['push']

jobs:
    codacy-analysis-cli:
        name: Codacy Analysis CLI
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@main
              
            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                node-version: '16.x'

            - name: Run Codacy Analysis CLI
              uses: codacy/codacy-analysis-cli-action@master
              
            - name: ESLint
              run: npx eslint .
